version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6380:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
